/**
 * End-to-end encryption for the shared bucket.
 *
 * File bytes are encrypted in the browser with a per-session AES-256-GCM
 * "content key" before they are uploaded, and decrypted after download, so the
 * server only ever stores ciphertext. The content key is generated by the
 * session owner and handed to each member after they join: every client holds a
 * non-extractable ECDH (P-256) identity keypair, publishes its public key, and
 * the content key is wrapped (ECDH -> AES-GCM) per recipient. The server only
 * relays public keys and wrapped blobs — it never sees the content key or
 * plaintext.
 *
 * SubtleCrypto is only available in secure contexts (HTTPS or localhost). Over
 * plain HTTP on a LAN/custom IP it is undefined; callers must check
 * `e2eeSupported` and fall back to plaintext when it is false.
 */

export const e2eeSupported =
  typeof crypto !== "undefined" && typeof crypto.subtle !== "undefined";

// Marks an encrypted blob so downloads can tell ciphertext from plaintext
// (e.g. files uploaded by a client without SubtleCrypto). Layout on the wire:
//   [MAGIC (8 bytes)][IV (12 bytes)][AES-GCM ciphertext + tag]
const MAGIC = new Uint8Array([0x48, 0x4f, 0x45, 0x31, 0x9a, 0x57, 0x2c, 0xe3]);
const IV_BYTES = 12;

const ECDH_PARAMS: EcKeyGenParams = { name: "ECDH", namedCurve: "P-256" };

// ---- base64 helpers --------------------------------------------------------

function toB64(buf: ArrayBuffer | Uint8Array): string {
  const bytes = buf instanceof Uint8Array ? buf : new Uint8Array(buf);
  let s = "";
  for (let i = 0; i < bytes.length; i++) s += String.fromCharCode(bytes[i]);
  return btoa(s);
}

function fromB64(str: string): ArrayBuffer {
  const bin = atob(str);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes.buffer;
}

// ---- IndexedDB key storage (survives reloads) ------------------------------

const DB_NAME = "handover-e2ee";
const STORE = "keys";

function openDb(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(DB_NAME, 1);
    req.onupgradeneeded = () => {
      if (!req.result.objectStoreNames.contains(STORE))
        req.result.createObjectStore(STORE);
    };
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}

async function idbGet<T>(key: string): Promise<T | undefined> {
  const db = await openDb();
  try {
    return await new Promise<T | undefined>((resolve, reject) => {
      const tx = db.transaction(STORE, "readonly");
      const req = tx.objectStore(STORE).get(key);
      req.onsuccess = () => resolve(req.result as T | undefined);
      req.onerror = () => reject(req.error);
    });
  } finally {
    db.close();
  }
}

async function idbSet(key: string, val: unknown): Promise<void> {
  const db = await openDb();
  try {
    await new Promise<void>((resolve, reject) => {
      const tx = db.transaction(STORE, "readwrite");
      tx.objectStore(STORE).put(val, key);
      tx.oncomplete = () => resolve();
      tx.onerror = () => reject(tx.error);
    });
  } finally {
    db.close();
  }
}

async function idbDel(key: string): Promise<void> {
  const db = await openDb();
  try {
    await new Promise<void>((resolve, reject) => {
      const tx = db.transaction(STORE, "readwrite");
      tx.objectStore(STORE).delete(key);
      tx.oncomplete = () => resolve();
      tx.onerror = () => reject(tx.error);
    });
  } finally {
    db.close();
  }
}

// ---- identity keypair (per slug) -------------------------------------------

const identityCache = new Map<string, CryptoKeyPair>();
const contentCache = new Map<string, CryptoKey>();

async function getIdentity(slug: string): Promise<CryptoKeyPair> {
  const cached = identityCache.get(slug);
  if (cached) return cached;
  const stored = await idbGet<CryptoKeyPair>(`identity:${slug}`);
  if (stored) {
    identityCache.set(slug, stored);
    return stored;
  }
  // Private key is non-extractable; the public key is always exportable.
  const pair = await crypto.subtle.generateKey(ECDH_PARAMS, false, [
    "deriveKey",
  ]);
  await idbSet(`identity:${slug}`, pair);
  identityCache.set(slug, pair);
  return pair;
}

/** This client's ECDH public key as base64 SPKI, ready to publish. */
export async function getPublicKeyB64(slug: string): Promise<string> {
  const pair = await getIdentity(slug);
  const spki = await crypto.subtle.exportKey("spki", pair.publicKey);
  return toB64(spki);
}

async function importPublicKey(b64: string): Promise<CryptoKey> {
  return crypto.subtle.importKey("spki", fromB64(b64), ECDH_PARAMS, false, []);
}

/** Derive a shared AES-GCM key-wrapping key from our private + their public. */
async function deriveKek(
  slug: string,
  theirPubB64: string
): Promise<CryptoKey> {
  const pair = await getIdentity(slug);
  const theirPub = await importPublicKey(theirPubB64);
  return crypto.subtle.deriveKey(
    { name: "ECDH", public: theirPub },
    pair.privateKey,
    { name: "AES-GCM", length: 256 },
    false,
    ["encrypt", "decrypt"]
  );
}

// ---- content key -----------------------------------------------------------

/** Generate a fresh session content key (extractable so it can be wrapped). */
export async function generateContentKey(slug: string): Promise<CryptoKey> {
  const key = await crypto.subtle.generateKey(
    { name: "AES-GCM", length: 256 },
    true,
    ["encrypt", "decrypt"]
  );
  await saveContentKey(slug, key);
  return key;
}

export async function loadContentKey(slug: string): Promise<CryptoKey | null> {
  const cached = contentCache.get(slug);
  if (cached) return cached;
  const stored = await idbGet<CryptoKey>(`content:${slug}`);
  if (stored) {
    contentCache.set(slug, stored);
    return stored;
  }
  return null;
}

export async function saveContentKey(
  slug: string,
  key: CryptoKey
): Promise<void> {
  contentCache.set(slug, key);
  await idbSet(`content:${slug}`, key);
}

export interface WrappedKey {
  wrapped: string;
  iv: string;
}

/** Wrap the content key for a recipient identified by their public key. */
export async function wrapContentKey(
  slug: string,
  theirPubB64: string,
  contentKey: CryptoKey
): Promise<WrappedKey> {
  const kek = await deriveKek(slug, theirPubB64);
  const raw = await crypto.subtle.exportKey("raw", contentKey);
  const iv = crypto.getRandomValues(new Uint8Array(IV_BYTES));
  const wrapped = await crypto.subtle.encrypt(
    { name: "AES-GCM", iv },
    kek,
    raw
  );
  return { wrapped: toB64(wrapped), iv: toB64(iv) };
}

/** Unwrap a content key delivered by a key-holder, and persist it. */
export async function unwrapContentKey(
  slug: string,
  theirPubB64: string,
  wrappedB64: string,
  ivB64: string
): Promise<CryptoKey> {
  const kek = await deriveKek(slug, theirPubB64);
  const raw = await crypto.subtle.decrypt(
    { name: "AES-GCM", iv: fromB64(ivB64) },
    kek,
    fromB64(wrappedB64)
  );
  const key = await crypto.subtle.importKey(
    "raw",
    raw,
    { name: "AES-GCM" },
    true,
    ["encrypt", "decrypt"]
  );
  await saveContentKey(slug, key);
  return key;
}

// ---- file content encryption ----------------------------------------------

/** Encrypt a file into a `MAGIC || IV || ciphertext` blob for upload. */
export async function encryptFile(file: File, key: CryptoKey): Promise<Blob> {
  const iv = crypto.getRandomValues(new Uint8Array(IV_BYTES));
  const plaintext = await file.arrayBuffer();
  const ciphertext = await crypto.subtle.encrypt(
    { name: "AES-GCM", iv },
    key,
    plaintext
  );
  return new Blob([MAGIC, iv, ciphertext]);
}

/** True if a downloaded buffer carries our encryption magic prefix. */
export function isEncrypted(buf: ArrayBuffer): boolean {
  if (buf.byteLength < MAGIC.length + IV_BYTES) return false;
  const head = new Uint8Array(buf, 0, MAGIC.length);
  for (let i = 0; i < MAGIC.length; i++) if (head[i] !== MAGIC[i]) return false;
  return true;
}

/** Decrypt a `MAGIC || IV || ciphertext` buffer back to the original bytes. */
export async function decryptToBytes(
  buf: ArrayBuffer,
  key: CryptoKey
): Promise<ArrayBuffer> {
  const iv = new Uint8Array(buf, MAGIC.length, IV_BYTES);
  const ciphertext = buf.slice(MAGIC.length + IV_BYTES);
  return crypto.subtle.decrypt({ name: "AES-GCM", iv }, key, ciphertext);
}

// ---- cleanup ---------------------------------------------------------------

/** Drop this session's keys from memory and IndexedDB (on leave / end). */
export async function clearSession(slug: string): Promise<void> {
  identityCache.delete(slug);
  contentCache.delete(slug);
  try {
    await idbDel(`identity:${slug}`);
    await idbDel(`content:${slug}`);
  } catch {
    // best-effort
  }
}

/** Trigger a browser "save as" for a decrypted blob. */
export function saveBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 10_000);
}
